//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olaglasses.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OlaGlassesEntities : DbContext
    {
        public OlaGlassesEntities()
            : base("name=OlaGlassesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCoupon> tblCoupons { get; set; }
        public virtual DbSet<tblFavourite> tblFavourites { get; set; }
        public virtual DbSet<tblglassPicture> tblglassPictures { get; set; }
        public virtual DbSet<tblOrderPrescription> tblOrderPrescriptions { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblReviewLike> tblReviewLikes { get; set; }
        public virtual DbSet<tblReview> tblReviews { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblVariation> tblVariations { get; set; }
        public virtual DbSet<ActivationCode> ActivationCodes { get; set; }
        public virtual DbSet<ForgetPassword> ForgetPasswords { get; set; }
        public virtual DbSet<tblSize> tblSizes { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblColors> tblColors { get; set; }
        public virtual DbSet<tblUserPrescription> tblUserPrescription { get; set; }
        public virtual DbSet<tblcart> tblcart { get; set; }
        public virtual DbSet<tblOrder> tblOrder { get; set; }
        public virtual DbSet<tblOrderDetails> tblOrderDetails { get; set; }
    
        public virtual ObjectResult<Sp_Get_Favourite_List_Result> Sp_Get_Favourite_List(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Favourite_List_Result>("Sp_Get_Favourite_List", useridParameter);
        }
    
        public virtual ObjectResult<Sp_Get_Five_Reviews_Result> Sp_Get_Five_Reviews()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Five_Reviews_Result>("Sp_Get_Five_Reviews");
        }
    
        public virtual ObjectResult<Sp_Get_Product_List_Result> Sp_Get_Product_List(Nullable<int> userid, string sticker)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            var stickerParameter = sticker != null ?
                new ObjectParameter("Sticker", sticker) :
                new ObjectParameter("Sticker", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Product_List_Result>("Sp_Get_Product_List", useridParameter, stickerParameter);
        }
    
        public virtual ObjectResult<Sp_Get_Product_List_Filter_Result> Sp_Get_Product_List_Filter(string productType, Nullable<int> userID, string cwhere)
        {
            var productTypeParameter = productType != null ?
                new ObjectParameter("ProductType", productType) :
                new ObjectParameter("ProductType", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var cwhereParameter = cwhere != null ?
                new ObjectParameter("cwhere", cwhere) :
                new ObjectParameter("cwhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Product_List_Filter_Result>("Sp_Get_Product_List_Filter", productTypeParameter, userIDParameter, cwhereParameter);
        }
    
        public virtual ObjectResult<Sp_Get_Product_List_Filter_Accessory_Result> Sp_Get_Product_List_Filter_Accessory(string cwhere)
        {
            var cwhereParameter = cwhere != null ?
                new ObjectParameter("cwhere", cwhere) :
                new ObjectParameter("cwhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Product_List_Filter_Accessory_Result>("Sp_Get_Product_List_Filter_Accessory", cwhereParameter);
        }
    
        public virtual ObjectResult<spgetorderDetails_Result4> spgetorderDetails(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgetorderDetails_Result4>("spgetorderDetails", orderIDParameter);
        }
    }
}
