//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olaglasses.Models
{
    using System;
    
    public partial class spgetorderDetails_Result3
    {
        public int OrderID { get; set; }
        public Nullable<int> userID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string Status { get; set; }
        public Nullable<int> IsPaid { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string OrderComments { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string UserAddress { get; set; }
        public int OrderDetailID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Productname { get; set; }
        public string ProductPrice { get; set; }
        public string BFname { get; set; }
        public string BLname { get; set; }
        public string BAddress { get; set; }
        public string BCity { get; set; }
        public string BState { get; set; }
        public string BPostalCode { get; set; }
        public string BPhone { get; set; }
        public string BEmail { get; set; }
        public string BCountry { get; set; }
        public string Vision { get; set; }
        public string LensType { get; set; }
        public string UV_Protection { get; set; }
        public string ProductTotal { get; set; }
        public Nullable<int> ProductVariation { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public string FrameColor { get; set; }
        public string ProductImage { get; set; }
        public Nullable<double> ShippingAmount { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<int> PrescriptionID { get; set; }
        public Nullable<double> r_sph { get; set; }
        public Nullable<double> r_cyl { get; set; }
        public Nullable<double> r_axis { get; set; }
        public Nullable<double> r_add { get; set; }
        public Nullable<double> l_sph { get; set; }
        public Nullable<double> l_cyl { get; set; }
        public Nullable<double> l_axis { get; set; }
        public Nullable<double> l_add { get; set; }
        public string prescription { get; set; }
        public Nullable<System.DateTime> prescriptionDate { get; set; }
        public Nullable<double> PD { get; set; }
        public string PDImage { get; set; }
        public string PrescriptionImage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
