//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olaglasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCoupon
    {
        public int CouponID { get; set; }
        public string CouponCode { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Description { get; set; }
        public string CouponStatus { get; set; }
        public string CouponLink { get; set; }
        public string CouponColor { get; set; }
        public Nullable<int> TimesUsed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Text { get; set; }
    }
}
