//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olaglasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcart
    {
        public int Cartid { get; set; }
        public int GlassID { get; set; }
        public int Variationid { get; set; }
        public int Quantity { get; set; }
        public string LensType { get; set; }
        public string VisionType { get; set; }
        public string UVProtection { get; set; }
        public double TotalAmount { get; set; }
        public int Userid { get; set; }
        public Nullable<double> r_sph { get; set; }
        public Nullable<double> r_cyl { get; set; }
        public Nullable<double> r_axis { get; set; }
        public Nullable<double> r_add { get; set; }
        public Nullable<double> l_sph { get; set; }
        public Nullable<double> l_cyl { get; set; }
        public Nullable<double> l_axis { get; set; }
        public Nullable<double> l_add { get; set; }
        public string lensType1 { get; set; }
        public Nullable<double> PD { get; set; }
        public string PDImage { get; set; }
        public string PrescriptionImage { get; set; }
        public string Title { get; set; }
        public string shape { get; set; }
        public string Colour { get; set; }
        public Nullable<double> Price { get; set; }
        public string ProductImagePath { get; set; }
        public string Size { get; set; }
        public string Productcategory { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Shippingamount { get; set; }
        public Nullable<double> GranTotal { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string prescription { get; set; }
        public Nullable<System.DateTime> prescriptionDate { get; set; }
        public Nullable<int> Extracharges { get; set; }
    }
}
