//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olaglasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderPrescription
    {
        public int PrescriptionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<double> r_sph { get; set; }
        public Nullable<double> r_cyl { get; set; }
        public Nullable<double> r_axis { get; set; }
        public Nullable<double> r_add { get; set; }
        public Nullable<double> l_sph { get; set; }
        public Nullable<double> l_cyl { get; set; }
        public Nullable<double> l_axis { get; set; }
        public Nullable<double> l_add { get; set; }
        public string lensType { get; set; }
        public Nullable<int> quantity { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string prescription { get; set; }
        public Nullable<System.DateTime> prescriptionDate { get; set; }
        public Nullable<double> PD { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PDImage { get; set; }
        public string PrescriptionImage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
