//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olaglasses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int GlassID { get; set; }
        public string Title { get; set; }
        public string shape { get; set; }
        public string Colour { get; set; }
        public string Material { get; set; }
        public string Brand { get; set; }
        public string Gender { get; set; }
        public string AdditionalInfo { get; set; }
        public string AvailableSize { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string OrignalCode { get; set; }
        public string Mgf_Code { get; set; }
        public string Rim { get; set; }
        public string Sticker { get; set; }
        public string Feature { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<int> ReleatedTo { get; set; }
        public Nullable<int> Clicks { get; set; }
        public string SellinClinic { get; set; }
        public string ImagePath { get; set; }
    }
}
